name: Test Coveralls

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - name: Install PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install dependencies
        run: composer install

      - name: create coverage
        run: composer test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2