on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version:"8.3

      - name: create coverage
        run: composer test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2